- include: ubuntu.yml
  when: ansible_os_family == 'Debian'

- include: centos.yml
  when: ansible_os_family == "RedHat"

- set_fact: ansible_python_interpreter=/usr/bin/python3

- name: Create db for "{{ app_user }}"
  postgresql_db:
    name: "{{ db_name }}"
  become_user: postgres

- name: Create db "{{ app_user }}" user
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ app_user }}"
    password: "{{ app_user_passwd }}"
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Set owner {{ db_name }}
  postgresql_owner:
    db: "{{ db_name }}"
    new_owner: "{{ app_user }}"
  become_user: postgres
